<a href="https://colab.research.google.com/github/selerqc/gogol-collab/blob/main/NumPy_Laboratory_Activities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [30]:
import numpy as np
print(np.array([[7,7], [7, 7]]))

[[7 7]
 [7 7]]


In [32]:
import numpy as np

print(np.arange(10,51,2))



[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [35]:
import numpy as np
print(np.eye(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
import numpy as np
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
import numpy as np
arr = np.arange(1,11)
print(arr[arr>5])

[ 6  7  8  9 10]


In [39]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[5 7 9]


In [41]:
import numpy as np
arr = [3, 9, 0, -1, 5]
print("Max:", np.max(arr))
print("Min:", np.min(arr))

Max: 9
Min: -1


In [44]:
import numpy as np
print(np.random.rand(9).reshape(3,3))

[[0.25986791 0.80623632 0.52039029]
 [0.52179679 0.74123454 0.07206599]
 [0.60545583 0.74189997 0.72310667]]


In [46]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])

print(arr*3)

[[ 3  6]
 [ 9 12]]


In [47]:
import numpy as np

arr = [[1, 2], [3, 4]]

print(np.array(arr))

[[1 2]
 [3 4]]


In [49]:
import numpy as np
arr = [10, 20, 30, 40, 50]

print("Mean:", np.mean(arr))
print("Meadian:",np.median(arr))
print("Standard Deviation:", np.std(arr))


Mean: 30.0
Meadian: 30.0
Standard Deviation: 14.142135623730951


In [52]:
arr = np.array( [5, 10, 15, 20])

print(arr[arr>10])

[15 20]


In [53]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


In [55]:
import numpy as np
print(np.array([[1, 2, 3], [4, 5, 6]]).flatten())

[1 2 3 4 5 6]
